apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: #PROJ#
spec: {}
status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-graph
rules:
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  - builds
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - secrets
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - project.openshift.io
  resources:
  - projects
  verbs:
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: k8s-graph
  namespace: #PROJ#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-graph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-graph
subjects:
- kind: ServiceAccount
  name: k8s-graph
  namespace: #PROJ#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-graph
  name: k8s-graph
  namespace: #PROJ#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-graph
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-graph
    spec:
      serviceAccountName: k8s-graph
      containers:
      - image: ghcr.io/kwkoo/k8s-graph:latest
        name: k8s-graph
        ports:
        - containerPort: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-graph
  name: k8s-graph
  namespace: #PROJ#
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-graph
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: k8s-graph
  name: k8s-graph
  namespace: #PROJ#
spec:
  port:
    targetPort: 8080
  to:
    kind: ""
    name: k8s-graph
    weight: null
status: {}
